src/components/mx-badge/mx-badge.tsx
src/components/mx-badge/readme.md
src/components/mx-badge/test/mx-badge.spec.tsx
vuepress/.vuepress/config.js
vuepress/components/data-display.md

This adds a new `mx-badge` component.  The badge can either be standalone/inline, or it can be wrapped onto an element to anchor it to a corner of that element.
I had to add two props, `tight` and `snug`, to tweak how far the badge is offset from the corner of the wrapped element.  I wish I could determine this automatically for the consumer, but I think trying to do so would make the component super fragile.
Similarly, the `squared` prop is based on the [standalone badges in the Figma file](https://www.figma.com/file/b36oTkOP6vI6uzLnc7Zd3T/Design-System-(Shirley)?node-id=15386%3A6232).  I believe the intent is to to use the more rounded look for numbers and the more squared look for text.
https://moxiworks.atlassian.net/browse/ENG-132962

ENG-132962 - Implement Badge component

---

src/components/mx-switch/mx-switch.tsx
src/tailwind/mx-checkbox/index.scss
src/tailwind/mx-radio/index.scss
src/tailwind/mx-switch/index.scss
vuepress/components/selection-controls.md

Switches:
- Added missing focus and active states
- Added `switch` ARIA role
- Fixed small dead zone in label by using padding instead of margin for the label text
- Replaced box-shadow with shadow utility class
- Tweaked the centering of the overlay circle (the `.slider::after` pseudoelement)
Checkboxes:
- Added missing focus state
- Added a tiny bit of `border-radius` to match the look in the Figma design
Radio Buttons:
- Added missing focus state
The added focus styles should just show up when tabbing with the keyboard.
While I was making changes to these, I also went ahead and updated the `selection-controls.md` to import the code snippets.

ENG-132177 - Selection Control Tweaks

---

src/tailwind/styles.css
tailwind.config.js
vuepress/components/buttons.md
vuepress/components/data-display.md
vuepress/components/inputs.md
vuepress/css-documentation/typography.md

- Fixed the `tracking-*` values for the `subtitle` classes.
- Moved `fontSize`, `letterSpacing`, and `spacing` tailwind config sections out of `extend`.
- Added `letterSpacing` values to our `text-*` utility classes.
- Removed `tracking-neg-0-5` and `tracking-neg-1-5` because you can always do `-tracking-0-5` and `-tracking-1-5`.
- Replaced all uses of `.my-5` (tailwind's 20px margin) in our docs with `.my-20` (our 20px margin).
- Made a lot of changes to `typography.md`, including a few typo fixes.

ENG-129852 - Typography & Tailwind Config Tweaks

---

src/components/mx-badge/readme.md
src/components/mx-tab-content/mx-tab-content.tsx
src/components/mx-tab-content/readme.md
src/components/mx-tab-content/test/mx-tab-content.spec.tsx
src/components/mx-tab/mx-tab.tsx
src/components/mx-tab/readme.md
src/components/mx-tab/test/mx-tab.spec.tsx
src/components/mx-tabs/mx-tabs.tsx
src/components/mx-tabs/readme.md
src/components/mx-tabs/test/mx-tabs.spec.tsx
src/tailwind/mx-tab/index.scss
src/tailwind/styles.css
vuepress/.vuepress/config.js
vuepress/components/tabs.md
vuepress/css-documentation/elevations.md

This adds `mx-tabs` and `mx-tab` components.  The parent `mx-tabs` component simply handles the fill vs. stack appearance (by switching between `grid` and `inline-grid`), as well as the indicator animation.
One thing I wasn't 100% sure on: I decided to use a `label` prop for the visible label, and an `aria-label` prop for icon-only tabs.  Alternatively, we could just have one `label` prop that always feeds into the `aria-label` attribute, but then the user would have to set another prop like `icon-only` or `hide-text` to hide the text.
https://moxiworks.atlassian.net/browse/ENG-133039

ENG-133039 Tab Components

---

src/components/mx-tabs/mx-tabs.tsx
src/tailwind/mx-input/index.scss
src/tailwind/mx-switch/index.scss
src/tailwind/ripple.scss
src/utils/utils.ts

This updates a few places to remove animation when the user prefers reduced motion:
- Label animation in `mx-input`
- The `mx-switch` slider animation
- Ripple (in buttons and tabs)
- Indicator animation in `mx-tabs` (via a new `queryPrefersReducedMotion` util since the animation is added with javascript)
Going forward, I've added this to a list of things to consider when working on new components.

Honor prefers-reduced-motion

---

src/components/mx-tabs/mx-tabs.tsx
src/utils/minWidthSync.ts
tailwind.config.js

This adds a `minWidthSync` helper that can be used to update components' `minWidths` state whenever the window width changes (e.g. `this.minWidths.md` becomes `true` when the window width is >= 720px).  Each component just has to call `minWidthSync.subscribeComponent(this)` in its `connectedCallback`.  Rather than register listeners for every component instance, all components that subscribe to the `minWidthSync` share the same listeners, and if all the components unsubscribe, then the listeners are removed to be extra sure we don't end up with memory leaks.
I updated `mx-tabs` to use this instead of its own `MediaQueryListener`.  The upcoming `mx-page-header` component will also use this.  I also updated our tailwind config to use the same `md` value for its breakpoint, and I moved the …

Sync component minWidths state

---

src/components/mx-button/mx-button.tsx
src/tailwind/variables/index.scss

This replaces most of the rgba colors with an opaque hex color.  I used a picker to double-check pretty much every color, so I also corrected a few colors that were already hex.  There are more unique color values in our variables file now because a color like `rgba(51, 51, 51, 0.87)` is `#434343` against the default `#f9f9f9` background, but it becomes `#454545` against the white background of a button.
I also noticed that some of the buttons had some extra letter spacing in figma, so I earmarked that fix onto this PR.

Hexify colors

---

src/components/mx-circular-progress/mx-circular-progress.tsx
src/components/mx-circular-progress/test/mx-circular-progress.spec.tsx
src/components/mx-linear-progress/mx-linear-progress.tsx
src/components/mx-linear-progress/test/mx-linear-progress.spec.tsx
src/tailwind/mx-circular-progress/index.scss
src/tailwind/mx-linear-progress/index.scss
src/tailwind/styles.css
src/tailwind/variables/index.scss
vuepress/.vuepress/config.js
vuepress/components/progress.md

This adds two progress indicator components: `mx-circular-progress` and `mx-linear-progress`.  Many of the specific easing values and animating timings were taken from https://github.com/material-components/material-components-web.

ENG-134175 - Progress Indicators

---

src/components/mx-input/mx-input.tsx
src/tailwind/mx-input/index.scss
src/tailwind/mx-toggle-button/index.scss
src/tailwind/variables/index.scss
src/utils/utils.ts
vuepress/components/inputs.md

- Added missing hover and disabled states to `mx-input`.
- Made changes to ensure the `label` in `mx-input` always has a `for` attribute that points to the `id` of the input.  This meant adding an `inputId` prop if the user wants to set that manually, as well as providing a default `id` via a new `uuidv4` utility function.
- Added a little bit more info to `inputs.md` and made the page more responsive.
Before:
After:
- Added a negative `outline-offset` to toggle buttons so the outline isn't clipped.
Before:
After:

Text Input Fixes, etc.

---

src/components/mx-checkbox/mx-checkbox.tsx
src/components/mx-checkbox/test/mx-checkbox.spec.tsx
src/tailwind/mx-checkbox/index.scss
src/tailwind/variables/index.scss
vuepress/components/selection-controls.md

- Added disabled and indeterminate states to `mx-checkbox`.  The indeterminate state is needed for the data table (un)check-all checkboxes.
- Added a `hideLabel` prop that visually hides the label, but leaves it accessible to screen readers.  This is also needed for the data table checkboxes.
- Tweaked the styling of the checked checkbox a little to better match the design.

Add disabled and indeterminate states to checkbox

---

src/components/mx-input/mx-input.tsx
src/components/mx-input/test/mx-input.spec.tsx
src/tailwind/mx-input/index.scss
src/tailwind/variables/index.scss
vuepress/components/inputs.md

- Added `readonly` prop, which sets the `input`'s `readonly` attribute, and changes the background color.
- Fixed the active state not getting set when an `mx-input` already has a value when it's created
- Fixed the disabled text color not getting applied to the `input` itself

ENG-135466 - Add readonly prop to mx-input

---

src/components/mx-select/test/mx-select.spec.tsx

This fixes a failing unit test that I broke with a139359e9e102ffcc77c6813c2fd0dd81f08466e (the `i` element was replaced with a `span` that wraps an SVG, so the selector in the unit test was wrong).

Fix failing mx-select unit test (due to recent icon change)

---

src/components/mx-input/mx-input.tsx
src/components/mx-input/test/mx-input.spec.tsx
src/tailwind/mx-input/index.scss
vuepress/components/inputs.md

This adds a `placeholder` prop to `mx-input` that is only used when there isn't a floating label (since the floating label serves as the placeholder).

Add placeholder prop to mx-input

---

src/components/mx-snackbar/mx-snackbar.tsx
src/components/mx-snackbar/test/mx-snackbar.spec.tsx
src/tailwind/mx-snackbar/index.scss
src/tailwind/styles.css
src/tailwind/variables/index.scss
src/utils/transitions.ts
tailwind.config.js
vuepress/.vuepress/config.js
vuepress/components/snackbars.md

This implements `mx-snackbar`.  The message content is added via the default slot, and the optional action button is placed inside the named `action` slot.
Before the snackbar loads, a "portal" element is appended to the body (if not already created), and the snackbar is moved inside that portal.  This ensures that the fixed positioning is relative to _the page_--not some other stacking context, which can happen if a parent component has a CSS transform applied, for example.
The other tricky part to this component is that multiple snackbars do not stack per Material Design.  Instead, they are queued and shown sequentially.  This queue is implemented as an array of deferred promises.  Whenever a snackbar closes, it resolves the next promise in the queue.

ENG-137505 - Snackbar Component

---

src/components/mx-checkbox/mx-checkbox.tsx
src/components/mx-radio/mx-radio.tsx
src/components/mx-switch/mx-switch.tsx
src/tailwind/mx-switch/index.scss
vuepress/components/selection-controls.md

Tweaked `mx-switch` a bit so that a multi-line label will now center with the switch.  I also tested long labels with checkboxes and radio buttons, and those just needed a `flex-shrink-0` class on the actual checkbox/button, but were otherwise good to go.

ENG-137681 - Fix selection control issues with long labels

---

src/components/mx-table-cell/mx-table-cell.tsx
src/components/mx-table-row/mx-table-row.tsx
src/components/mx-table/mx-table.tsx
src/components/mx-table/test/mx-table.spec.tsx
src/tailwind/mx-table/index.scss
src/tailwind/variables/index.scss
vuepress/components/tables.md

This is a pretty heavy refactor, mostly of the `mx-table-row` component.
Long-winded explanations of a few big changes that may or may not help:
- The row checkbox and drag handle used to be in separate grid cells, but the design of the indenting requires them to be in the same grid cell as the first `mx-table-cell`.  Since that first `mx-table-cell` can come from the default slot, I have to actually move the element during `componentWillRender` (see `wrapFirstColumn()`).
- Similarly, the slotted, nested rows need to be outside the `rowEl` container that collapses on mobile, so I have to also move nested `mx-table-row` elements during `componentWillRender` (see `moveNestedRows()`).  I could have used a named slot specifically for the child rows to avoid this, but there still would have …

Nested table rows

---

src/components/mx-table-cell/mx-table-cell.tsx
src/components/mx-table-row/mx-table-row.tsx
src/components/mx-table/mx-table.tsx
src/components/mx-table/test/mx-table.spec.tsx
src/tailwind/mx-table/index.scss
src/tailwind/variables/index.scss
vuepress/components/tables.md

This adds a `subheader` prop to `mx-table-row`, which causes the row to be styled per the design.  Any rows nested inside a subheader row are not indented.
In testing this, I noticed some bugs with single-column tables (the mobile rows showed the accordion button even though there was no content to reveal), so those have been fixed.
I discovered that the confusing combination of pseudo-selectors I was using for the rounded bottom corners of non-paginated tables didn't work when the last row was a nested row, so I ended up toggling a `last-row` class using javascript instead.
And finally, I added a color variable for the row drag handle, and I set it to match the examples in the Stellar design.

Table subheader rows

---

src/components/mx-table/mx-table.tsx
src/components/mx-table/test/mx-table.spec.tsx

This updates the `allRowsChecked` and `someRowsChecked` getters to work with rows that are purely slotted.  The check-all checkbox uses those two getters for its `checked` and `indeterminate` states.  I added a unit test for this as well.

Fix check-all checkbox state for slotted rows

---

src/components/mx-table/mx-table.tsx
vuepress/components/tables.md

This adds an `isActionColumn` property to the `ITableColumn` interface for table column definitions.  This really only does two things:
- The column is excluded from the mobile column navigation, so rows must be expanded to access the column's contents on mobile.
- Typically, columns are always left-aligned on mobile regardless of the `align` value, but `isActionColumn` allows the column to be right- or center-aligned on mobile.
I also fixed the `cellClass` property so that it is applied to slotted cells, not just the ones generated via the `rows` prop.

Add `isActionColumn` property to `ITableColumn` for custom action columns

---

src/components/mx-dialog/mx-dialog.tsx
src/components/mx-dialog/test/mx-dialog.spec.tsx
src/components/mx-modal/mx-modal.tsx
src/tailwind/mx-dialog/index.scss
src/tailwind/styles.css
src/tailwind/variables/index.scss
src/utils/bodyScroll.ts
vuepress/.vuepress/config.js
vuepress/components/dialogs.md
vuepress/components/modals.md

This implements `mx-dialog`, which exposes two methods: `alert()` and `confirm()`.  These are Promise-based replacements for the `Window.alert()` and `Window.confirm()` methods.  The methods are pretty much identical, but `alert()` defaults to just an "Okay" button, and `confirm()` defaults to both an "Okay" and a "Cancel" button.  The second argument is an options object with properties for a `heading`, `confirmLabel`, and `cancelLabel`.
I also added a new module with some methods for locking and unlocking scrolling on the `body` while dialogs/modals are open.  It tries to prevent layout shifts caused by the removal of the scrollbar by adding the appropriate amount of padding to the right side, but there still may be some unavoidable shifting with elements that are `fixed`/`absolute` …

Implement Dialog Component

---

src/components/mx-table-row/mx-table-row.tsx
src/components/mx-table/mx-table.tsx
src/components/mx-table/test/mx-table.spec.tsx
vuepress/components/tables.md

This adds two features to `mx-table`:
- Combining the `rows` prop with a new `groupBy` prop allows for the automatic nesting of rows under subheader rows.
- Unless `mutateOnDrag` is set to `false`, the `rows` array is now mutated by default when rows are reordered via drag and drop.  This can be combined with the aforementioned `groupBy` prop to reorder grouped rows.
Some of the supporting changes:
- Added a `rowIndex` prop to `mx-table-row` that is set by the parent `mx-table` in order to make reordering the `rows` array easier.
- Added a new method called `getNestedRowIndexes` to `mx-table-row`, which is used for the reordering of entire row groups (when the subheader row is dragged).
- Quite a few variables were renamed to help distinguish between a row's index (its index in the `rows` …

Table grouping and `rows` reordering

---

src/components/mx-date-picker/mx-date-picker.tsx
src/components/mx-dropdown-menu/mx-dropdown-menu.tsx
src/components/mx-input/mx-input.tsx
src/components/mx-modal/mx-modal.tsx
src/components/mx-select/mx-select.tsx
src/components/mx-time-picker/mx-time-picker.tsx

Just a couple random fixes:
- Fixed several components having both a `border` and a `border-2` class when focused or in an error state.  I noticed in devint that the `border-2` class wasn't always winning the specificity war on focused text inputs.
- Fixed modal transitions.  I'm not sure how these were working for me before 🤷.  The `transition` getter is now two getters: `openTransition` and `closeTransition`.

Fix input border widths and modal transitions

---

src/components/mx-table/mx-table.tsx
vuepress/components/tables.md

- Fixed the `onRowMove` event firing before the `HTMLMxTableElement.rows` property was updated.
- Fixed reordering that would render correctly, but was actually not grouped correctly in the updated `rows` array (because the rows were spliced above the first row in the target group instead of below the last row).
- Made the draggable grouped rows example in the docs much better.

Table row dragging fixes

---

src/components/mx-page-header/mx-page-header.tsx

Safari 15.0 (and maybe earlier?) are having trouble with one particular CSS grid in the Page Header component.  You can see it on the Page Headers page at < 768px, and in the Modal component's `header-center` slot example.  I've tried coming up with a minimum reproduction in codepen to no avail.  It seems to be a combination of a grid with `align-items: center` inside a column flex box that is inside another flex box... and something else.  The end result is that the grid height extends way beyond its parent.
In any case, I came up with a workaround.  When there is only one child element (and no need for the grid), the element in question uses flex instead.  And when it does need to be a grid, setting it to `height: 100%` makes it behave normally.

Fix Page Header grid bugginess in Safari

---

src/components/mx-modal/mx-modal.tsx
src/utils/transitions.ts

This replaces the repetitious `SLIDE_IN_FROM_RIGHT`, `SLIDE_OUT_TO_LEFT`, etc. constants with a function for generating those `TransitionOptions`.  The upcoming `mx-banner` component slides in from the top, so I figured it was time to clean this up.

Refactor slide transition options

---

tailwind.config.js

The `focus:border-2` class is not generated by default (if not using JIT), so the `mx-search` instances in `devint` do not have 2px border on focus (similar to #63).

Add focus variant to tailwind borderWidth classes

---

src/components/mx-checkbox/mx-checkbox.tsx
src/components/mx-checkbox/test/mx-checkbox.spec.tsx
src/components/mx-image-upload/mx-image-upload.tsx
src/components/mx-table-row/mx-table-row.tsx
src/tailwind/mx-menu-item/index.scss
src/tailwind/mx-menu/index.scss
src/utils/transitions.ts

- Reverted back to using vertical padding in `mx-menu` instead of applying margin to the first and last menu items.  I noticed in nucleus that the `mx-menu-item` elements were sometimes wrapped in other elements due to helpers like `button_to`, which would trip up the `:first-child` and `:last-child` selectors I was using.  To get around the original problem of not wanting padding in an empty menu, I simply used `:not(:empty)`.  Seems so obvious now haha.
- Updated a table `onClick` handler to not trigger (un)checking a row when clicking an `<a>` in that row.
- Fixed a non-clickable area in `mx-image-upload`; the `<input type=file>` needed a `w-full` class in addition to `inset-0`.
- Added an additional check in `executeTransition` to prevent exceptions when an element is removed …

Random Fixes 2021-11-30

---

src/components/mx-dropdown-menu/mx-dropdown-menu.tsx
src/components/mx-dropdown-menu/test/mx-dropdown-menu.spec.tsx
src/components/mx-icon-button/mx-icon-button.tsx
src/components/mx-menu-item/mx-menu-item.tsx
src/components/mx-menu-item/test/mx-menu-item.spec.tsx
src/tailwind/mx-menu-item/index.scss
src/tailwind/variables/index.scss
vuepress/components/dropdowns.md
vuepress/components/menus.md

This adds a `subtitle` prop to `mx-menu-item`.  I also added a `getValue` method for getting the default slot's inner text; this is now used by `mx-dropdown-menu` to update its value.
I'm also sneaking in an `appearance-none` class for icon buttons, which should hopefully get them looking good again in the latest version of Safari.

Add subtitle prop to mx-menu-item

---

src/components/mx-button/mx-button.tsx
src/components/mx-button/test/mx-button.spec.tsx
src/components/mx-chip/mx-chip.tsx
src/components/mx-chip/test/mx-chip.spec.tsx
src/components/mx-dropdown-menu/test/mx-dropdown-menu.spec.tsx
src/components/mx-icon-button/mx-icon-button.tsx
src/components/mx-menu-item/mx-menu-item.tsx
src/components/mx-menu-item/test/mx-menu-item.spec.tsx
src/components/mx-menu/mx-menu.tsx
src/components/mx-page-header/mx-page-header.tsx
src/components/mx-tab/mx-tab.tsx
src/components/mx-tab/test/mx-tab.spec.tsx
src/components/mx-table/mx-table.tsx
src/components/mx-toggle-button/mx-toggle-button.tsx
src/components/mx-toggle-button/test/mx-toggle-button.spec.tsx
src/tailwind/mx-button/index.scss
src/tailwind/mx-chip/index.scss
src/tailwind/mx-icon-button/index.scss
src/tailwind/mx-menu-item/index.scss
src/tailwind/mx-tab/index.scss
src/tailwind/mx-toggle-button/index.scss
tailwind.config.js
vuepress/components/menus.md

This addresses some ARIA issues:
- Unlike attributes like `required`, boolean _ARIA attributes_ like `aria-disabled` and `aria-selected` should be explicitly set to `'true'` per the spec, so I've fixed that in a bunch of components/CSS selectors.
- Updated `mx-menu` and `mx-menu-item` to use the `listbox` and `option` roles respectively when they are inside an `mx-dropdown-menu`.  Otherwise, they still use the `menu` and `menuitem` roles.  I've also corrected the use of `aria-selected` vs. `aria-checked` so that `aria-selected` is used for the selected option in an `mx-dropdown-menu`, and `aria-checked` is used for a `checked` menu item.

Fix ARIA boolean values & Dropdown Menu roles

---

package.json
src/components/mx-chart/mx-chart.tsx
src/components/mx-chart/test/mx-chart.spec.tsx
vuepress/.vuepress/config.js
vuepress/components/charts.md

This adds an `mx-chart` component that serves as a wrapper for [Chart.js](https://www.chartjs.org/).  I left it very unopinionated for now.  We can always bake in some default options/colors if we want as we flesh those out.

ENG-140025 - Charts

---

src/components/mx-dialog/mx-dialog.tsx
src/components/mx-dialog/test/mx-dialog.spec.tsx
src/tailwind/mx-dialog/index.scss
src/tailwind/variables/index.scss
src/utils/transitions.ts
tailwind.config.js
vuepress/components/dialogs.md

This adds the ability to markup advanced dialog layouts via slots.
- Added a default slot, as well as `heading` and `buttons` slots to `mx-dialog`.
- Added an `isOpen` prop for toggling the dialog in lieu of using the existing methods.
- Added a `modalClass` prop for adding classes to the inner modal element.
- The dialog content is now scrollable.
- Added a CSS variable for the color of the dialog scroll thumb.
- An `mxClose` event is now emitted after the dialog closes.
- Updated the tailwind config to generate `max-h-*` classes for all the spacing values and added a 480px/30rem value.
- Added back a previously removed `requestAnimationFrame` call in `executeTransition` that is needed for these dialogs to fade in consistently.

ENG-140494 - Implement advanced (slot-based) dialogs

---

src/components/mx-page-header/mx-page-header.tsx
src/tailwind/mx-page-header/index.scss

This change makes it so `mx-page-header` will automatically set the `xl` prop for slotted buttons based on the viewport width.  Buttons rendered via the `buttons` prop already have this behavior, so it makes sense to extend it to the slotted buttons, especially since this behavior would be a pain to implement in the host app.
I've also added some additional styling for the `[slot='buttons']` container so the button order will reverse on mobile (just like the buttons rendered via the `buttons` prop), and the button spacing should also be consistent now.
Corresponding PR in nucleus: https://github.com/moxiworks/nucleus/pull/70

ENG-140616 - Set page header slotted button `xl` prop automatically

---

vuepress/examples/grid.md

This adds the [Dashboard Grid example](https://www.figma.com/file/b36oTkOP6vI6uzLnc7Zd3T/Design-System-(Shirley)?node-id=22817%3A102452) from Figma to the responsive grid examples page.
I also updated the other examples on the page to use the vuepress region code snippet magic.

ENG-140024 - Dashboard Grid

---

src/components/mx-date-picker/mx-date-picker.tsx
src/components/mx-page-header/mx-page-header.tsx
src/components/mx-time-picker/mx-time-picker.tsx

Exception 1: Disconnecting the ResizeObserver isn't necessary since the only observed element is being removed, so I can just kill this line that is causing exceptions.
Exception 2: I couldn't reproduce, but the exception is from the `datepicker()` call, and the only node we're passing in is `this.inputEl`, so I'm fairly certain that adding a check for `inputEl` before calling `datepicker()` will prevent this.  Probably a timing thing when switching views.
I'm also removing the `required` attributes from the pickers in this PR.  This means Firefox will show clear buttons, but it's a necessary trade-off for functionality.
[ENG-140761](https://moxiworks.atlassian.net/browse/ENG-140761)

ENG-140761 - Fix page header and date picker exceptions

---

src/components/mx-table/mx-table.tsx

Collapsed table rows on mobile use `max-height` to achieve the collapsed effect.  However, that `max-height` was not being updated when switching the exposed column, which meant taller contents would get clipped.
This change introduces a `forceUpdate` call on each row whenever the exposed column is switched.
Before:
After:

ENG-140813 - Force update rows when switching exposed column

---

src/tailwind/mx-pagination/index.scss
src/tailwind/mx-radio/index.scss
src/tailwind/mx-search/index.scss
src/tailwind/mx-switch/index.scss
src/tailwind/mx-table/index.scss
src/tailwind/variables/index.scss

I noticed the text looked a bit darker in the nucleus tables, and I realized the component wasn't using the `--mds-text-table` variable at all.  I then temporarily set the design system to use a red body color and discovered several other places where we were missing explicit text colors.

ENG-140809 - Fix text color for several components

---

src/components/mx-table-row/mx-table-row.tsx
vuepress/components/tables.md

This will be used to remove the drag handle from the page variant rows in nucleus.

ENG-140807 - Add `doNotDrag` prop to `mx-table-row`

---

src/components/mx-image-upload/mx-image-upload.tsx
src/components/mx-image-upload/test/mx-image-upload.spec.tsx
vuepress/components/uploads.md

In some designs, we don't want the `mx-image-upload`'s Upload button to be a "contained" type (which looks like a primary button), so this change adds an `uploadBtnType` prop for changing the `btnType` prop of that inner `mx-button`.

ENG-140950 - Add `uploadBtnType` prop to `mx-image-upload`

---

src/tailwind/variables/index.scss
tailwind.config.js

Adding a couple utility classes around the error colors defined in the design system.  The `.text-error` class will be needed in nucleus for sure.

ENG-140938 - Add `.bg-error` and `.text-error` utility classes

---

src/utils/portal.ts
src/utils/test/portal.spec.ts

This change prevents the portal from being styled as an icon, which was causing a small black square to appear.

ENG-140937 - Remove `mds-` prefix from portal class

---

src/components/mx-table/mx-table.tsx

This fixes the bottom `border-radius` of the table when the last row is a collapsed, nested row.  I noticed this in nucleus when the last row in the Pages list was a variant.  I also moved this last-row stuff to a separate method.
Before (see the bottom non-rounded corners):
After:

ENG-140815: Only apply `.last-row` class to visible rows

---

src/components/mx-switch/mx-switch.tsx
vuepress/components/selection-controls.md

This is needed in nucleus for the "Agreement Options" switch.  Plus. `mx-checkbox` has this prop, so it only makes sense for the switch to have it as well.
I will also update the rails view component.

ENG-141053 - Add `labelClass` prop to `mx-switch`

---

src/components/mx-badge/mx-badge.tsx

This fixes badges that were being positioned as if they were anchored to a slotted element even when there was no slotted element.  This bug showed up in nucleus for the New/Updated badge on the Product tile preview.
The technical nitty gritty: When there is no slotted element, then `this.element.firstElementChild` will be `null`, but _only during the first render cycle_.  In subsequent renders, the first element in the component template will then be detected as the first child element.  Because I originally implemented `isStandalone` as a getter, that meant `isStandalone` would return `true` once the component went through more than one render cycle.  So to fix the issue, I just have to set `isStandalone` only once during `componentWillLoad`.  This issue did not show up in the …

ENG-141047 - Fix badge `isStandalone`

---

src/components/mx-tab/mx-tab.tsx
src/components/mx-tabs/mx-tabs.tsx
src/tailwind/mx-tab/index.scss

The tabs in the design system originally looked like they had explicit widths in Figma (because the example labels were all the same width), but they actually should have horizontal padding and varying widths.  This should fix the tabs in nucleus being too tight.
I also noticed that the `--mds-text-tab-icon` color was being applied to the tab badge (because it is now an `<i>` element), so I fixed that as well.

ENG-141045 - Replace mx-tab explicit width with horizontal padding

---

src/components/mx-table-row/mx-table-row.tsx

This fixes a bug where collapsed, nested rows are visible after switching to/from the mobile UI (resizing the window).

ENG-141043 - Hide collapsed nested rows when `minWidths` changes

---

src/components/mx-image-upload/mx-image-upload.tsx
src/components/mx-image-upload/test/mx-image-upload.spec.tsx
vuepress/components/uploads.md

These changes will make `mx-image-upload` easier to use.

ENG-141026 - Add `assistive-text` prop and `mxThumbnailChange` event to `mx-image-upload`

---

src/components/mx-table-row/mx-table-row.tsx

This changes the `MxTableRow.toggle` method to just set the collapse/expand duration to `0` if `skipTransition` is set to `true`.
This should fix the nucleus page variant rows doing the collapse animation every time the pages admin list loads.

ENG-141095 - Fix row toggle always animating

---

src/components/mx-image-upload/mx-image-upload.tsx

Not sure how I missed this earlier, but this fix puts the dropzone width on the actual dropzone wrapper.  This allows the assistive text to be wider than the dropzone/thumbnail.
Before
After

Move explicit width to dropzone wrapper

---

src/components/mx-image-upload/mx-image-upload.tsx

Changing `mx-image-upload` to `display: block` so that setting the dropzone `width` to a percentage works correctly even if the parent container is not a flexbox.
Before (`width` prop is set to 100%):
After:

ENG-141239 - Change Image Upload to `display: block`

---

src/components/mx-modal/mx-modal.tsx

Buttons in the modal footer should now automatically become `xl` on larger screens, even if they're passed in via the `footer-right` slot instead of the `buttons` prop.

ENG-141233 - Automatically set `xl` for slotted footer buttons

---

src/components/mx-modal/mx-modal.tsx
src/tailwind/mx-modal/index.scss

This fixes the `large` prop on `mx-modal` so that it always fills the screen (minus a 40px margin) regardless if the modal content is small.

ENG-141230 - Stretch large modals to fill screen

---

src/components/mx-modal/mx-modal.tsx

This fixes the issue where the modal heading was being constrained to 1/3 of the modal width (due to the modal always passing center slot content to the inner Page Header component).  I also had to add a `.flex-shrink-0` class to that inner Page Header to make sure it expands vertically whenever the heading actually needs to wrap.

ENG-141215 - Fix modal heading wrapping

---

src/components/mx-confirm-input/mx-confirm-input.tsx

On mobile devices (that cannot hover), there is no way to tell that an `mx-confirm-input` is editable, so we need to show the edit icon even if the element isn't hovered.
The [design for the Categories modal in nucleus](https://www.figma.com/file/ZQCgBp9weynQ7981oseA6s/ENG-134945-%7C-Apps-Admin-Page?node-id=196%3A145675) implies this behavior.

Always show `mx-confirm-input` edit icon on mobile

---

src/components/mx-button/mx-button.tsx
src/components/mx-icon-button/mx-icon-button.tsx

I partially fixed this before by adding `.appearance-none` to the `button` element inside `mx-icon-button`.
However, the tailwind reset rules apply `appearance: button` to `[type=button], [type=reset], [type=submit], button`.  This means the host elements for `mx-icon-button` and `mx-button` will get that styling if you explicitly set the `type` prop (i.e. `<mx-icon-button type="button">`).
None of the mds examples set the `type` explicitly, which is why this problem was only showing up in nucleus (and why I thought I had fixed it before).
Before:
After:

ENG-141185 - Fix Safari button appearance

---

src/components/mx-dropdown-menu/mx-dropdown-menu.tsx
src/components/mx-select/mx-select.tsx
src/tailwind/mx-dropdown-menu/index.scss
src/tailwind/mx-select/index.scss

Adding a 328px `min-width` to the `mx-dropdown-menu` and `mx-select` components.  This will ensure the components have a reasonable amount of width when they are not allowed to stretch otherwise.
Before:
After:

ENG-141282 - Add min-width to dropdown/select components

---

src/tailwind/mx-table/index.scss

This allows multiple controls to be placed inside the table's search slot.  This will eliminate the need for putting a negative margin on the Roster admin dropdown next to the search input, which is causing some extra horizontal scrolling.

ENG-141481 - Change search slot width to min-width

---

src/components/mx-table-row/mx-table-row.tsx
src/components/mx-tooltip/mx-tooltip.tsx

In addition to the previous changes merged with #102, this should finally fix the page variant rows animating on page load in nucleus.
I'm also changing `mx-tooltip`'s host element to `inline-flex` so it doesn't add line height to the wrapped element and mess up vertical centering for those elements.

ENG-141095 - Do not animate row nesting when min-width changes

---

src/components/mx-button/mx-button.tsx
src/components/mx-button/test/mx-button.spec.tsx
src/components/mx-image-upload/test/mx-image-upload.spec.tsx
src/tailwind/mx-button/index.scss
src/tailwind/variables/index.scss
vuepress/components/badges.md
vuepress/components/buttons.md
vuepress/components/menus.md
vuepress/components/snackbars.md
vuepress/components/tables.md
vuepress/components/uploads.md

This renames the "action" `btnType` to "simple".  However, "action" is still treated as an alias for "simple" in order to not break anything.
https://www.figma.com/file/b36oTkOP6vI6uzLnc7Zd3T/Design-System-(Shirley)?node-id=15124%3A73
I'm also sneaking in fixes for a couple broken `mx-image-upload` unit tests (caused by #101).

ENG-141438 - Action buttons are now called Simple buttons

---

src/components/mx-radio/mx-radio.tsx
src/components/mx-switch/mx-switch.tsx
vuepress/components/selection-controls.md

This is needed for the EULA agreement options in nucleus (the radio button labels need a `.subtitle3` class).

Add labelClass prop to mx-radio

---

src/components/mx-icon-button/mx-icon-button.tsx
src/components/mx-icon-button/test/mx-icon-button.spec.tsx
src/tailwind/mx-icon-button/index.scss
vuepress/components/buttons.md

Similar to `mx-button`, this updates `mx-icon-button` to support rendering as an `<a>` instead of `<button>` if the new `href` prop is set.  This will be needed to make nucleus more compliant to accessibility standards.

ENG-141837 - Allow icon buttons to be links (via new `href` prop)

---

src/utils/utils.ts

This updates the data attribute propagation (for components that wrap form elements) so that hyphens are not lost.

ENG-141900 - Preserve hyphens when propagating data attributes

---

src/components/mx-chip/mx-chip.tsx

This ensures that if a choice chip re-renders independently of its parent chip group, it will have the correct `selected` value.
This happens in nucleus right now for the Type chip group on the Product admin form.  It only happens when you first open the form from the product list (but not if you refresh the page).

ENG-141903 - Ensure chip-group chip selected value persists

---

src/components/mx-dropdown-menu/mx-dropdown-menu.tsx
src/components/mx-page-header/mx-page-header.tsx
src/components/mx-pagination/mx-pagination.tsx
src/components/mx-table-row/mx-table-row.tsx
src/components/mx-table/mx-table.tsx
src/components/mx-time-picker/mx-time-picker.tsx

Fixes #130
Updated `mx-dropdown-menu`, `mx-time-picker`, `mx-page-header`, `mx-table`, and `mx-table-row`.

Don't emit `mxClose` event from components that wrap menus

---

src/components/mx-search/mx-search.tsx
src/components/mx-search/test/mx-search.spec.tsx
vuepress/components/search.md

This change add an `mxClear` event to the `mx-search` clear button click.

ENG-142019 - Add mxClear event to mx-search

---

src/components/mx-button/mx-button.tsx
src/components/mx-button/test/mx-button.spec.tsx
src/components/mx-icon-button/mx-icon-button.tsx
src/components/mx-icon-button/test/mx-icon-button.spec.tsx
vuepress/components/buttons.md

This adds a `form` prop that sets the `form` attribute on the inner `button`.  This will allow us to have submit buttons in modal footers, for example, that are outside the `form` element.

ENG-142086 - Add form prop to buttons

---

src/tailwind/mx-modal/index.scss
vuepress/components/modals.md

Large modals will now have a max width of 1200px.  This is needed for the program info modals in nucleus.

ENG-142335 - Set large modal max width to 1200px

---

src/components/mx-page-header/mx-page-header.tsx
src/components/mx-search/mx-search.tsx
src/components/mx-toggle-button-group/mx-toggle-button-group.tsx
src/components/mx-toggle-button-group/test/mx-toggle-button-group.spec.tsx
vuepress/components/buttons.md

- Add `required` prop to toggle button group that prevents deselecting once a selection has been made (needed for nucleus preview modal device toggles) ENG-142597
- Prevent modal heading from overlapping Close button ENG-142609
- Added a missing aria-label to the mx-search clear button

Fixes from nucleus QA

---

package.json

`npm-watch` is used in our scripts, but it's not in our `package.json`.  This tripped up Michelle.

Add npm-watch as a dev dependency

---

src/utils/popover.ts

This changes the positioning for popovers from `absolute` to `fixed`.  This affects menus, tooltips, and the date picker's calendar popover.  The issue with using `absolute` was that if a parent container is set to `overflow: hidden`, the menu would sometimes be clipped.  For `overflow: auto`, the menu might cause unwanted scrolling.
I have not found any downsides to switching the positioning strategy.  Everything seems to work just fine. 🤞
@iamjpg This should fix that issue you had at one time when you were working on the filter dropdowns.

ENG-143238 - Use fixed popovers instead of absolute

---

src/components/mx-table/mx-table.tsx
src/components/mx-table/test/mx-table-mobile.spec.tsx
vuepress/components/tables.md

A couple of the tables in nucleus use an alternate layout on mobile for the search and filter slots.  I've added a new prop to enable this layout called `mobileSearchOnTop`.  The search slot is moved to the top row by itself, and the filter slot then shares the second row with the (un)check-all checkbox if present.
I debated about adding more granular props to control the grid layout of the operations bar, but it would have been pretty complex because we only want to affect small viewports and all of these grid items are optional.  Plus, the whole point of having the operations bar in the table component is for it to be somewhat consistent and opinionated.
I also reordered the prop definitions in `mx-table.tsx` so they're alphabetized since we're now up to 29(!) props.
Default mobile …

ENG-142283 & ENG-143125 - Add `mobileSearchOnTop` alternate layout for table operations bar

---

src/components/mx-table-row/mx-table-row.tsx

The `.h-full` class on the `.table-row-indent` was causing the exposed cell's grid row to expand beyond the `max-height` of the parent table row.
Before:
After:

ENG-143467 / ENG-143471 - Fix mobile table rendering in Safari/iOS

---

src/components/mx-button/mx-button.tsx
src/components/mx-button/test/mx-button.spec.tsx

Data attributes on the `<mx-button>` host element are applied to the inner `<button>` element, but they're currently not applied to the `<a>` element for buttons that are links.  This is why @aroop had trouble with [these Add buttons](https://github.com/moxiworks/nucleus/commit/5eda2cf60e1c087e1714a6dd846e04598291f5f4#diff-acc6fce6424cae9cf9fef07bcf9210bfa4aec4309bc75a18a78fae846b301312R46-R47).

Propagate mx-button data attributes to <a> as well

---

src/components/mx-dropdown-menu/test/mx-dropdown-menu.spec.tsx
src/components/mx-menu-item/mx-menu-item.tsx
src/components/mx-menu-item/test/mx-menu-item.spec.tsx
src/components/mx-menu/mx-menu.tsx
src/components/mx-menu/test/mx-menu.spec.tsx

This updates `mx-menu` and `mx-menu-item` to apply the `menu` and `menuitem` ARIA roles to the most appropriate elements.  Ideally, the `menu` and `menuitem` should be immediately related, but may be separated by an element with `role="none"` or `role="presentation"`.
For this reason, the scrolling element that wraps the `mx-menu`'s slot now has the `menu` role, and the `mx-menu-item` host element now has `role="none"`.  One exception I've added is when the `mx-menu-item` is wrapped in an `<a>`, then the `role="menuitem"` is applied to the link.
I've also fixed the `aria-haspopup` attribute that wasn't always getting applied, and I added `aria-expanded` to menu items that open sub-menus.

ENG-143561 - Address menu/menuitem role issues

---

src/components/mx-table-row/mx-table-row.tsx

This fixes an issue with a previous fix (https://github.com/moxiworks/mds/pull/152).  Not sure how I missed this, but we do in fact need the indent elements to be `height: 100%`, but only on larger screens.
Before:
After:

ENG-143595 - Set indent element to 100% height on non-mobile

---

src/components/mx-table-row/mx-table-row.tsx
src/components/mx-table/mx-table.tsx
src/tailwind/mx-table/index.scss
src/tailwind/variables/index.scss
vuepress/components/tables.md

This adds a button to subheader rows for collapsing/expanding the grouped rows.  This will make it easier to reorder categories in nucleus when there are a lot of products in each category.

ENG-143624 - Collapse/expand grouped rows under subheaders

---

src/components/mx-table-row/mx-table-row.tsx
src/tailwind/mx-table/index.scss

Not sure how I didn't see this when originally testing locally, but the mobile row styling broke when I added an extra `div` around the first `mx-table-cell`.
Instead of moving the first `mx-table-cell` into `this.firstCellTarget`, I'm now doing a `replaceChild` to replace `this.firstCellTarget`.  It should also be a bit more performant since it will now only happen once whenever the entire row needs re-rendering.
I also noticed that the accordion animation was laggy when there are a lot of nested rows, so I added `will-change: max-height`, which seems to help a lot.
Before:
After:

ENG-144264 - Wrap first column without extra div

---

src/components/mx-table-cell/mx-table-cell.tsx
src/components/mx-table-row/mx-table-row.tsx

- Fixed right side of table column contents sometimes getting clipped. ENG-144355
- Fixed subheader row children having crazy heights in Safari/iOS (basically the same bug as https://github.com/moxiworks/mds/pull/152, but for the new collapse/expand button instead of the indent element). ENG-144273

Table fixes

---

vuepress/components/menus.md

This adds another autocomplete menu example that shows results grouped under headings.

Add autocomplete menu example with headings

---

src/components/mx-button/mx-button.tsx
src/components/mx-table/mx-table.tsx
src/tailwind/mx-table/index.scss

This fixes overflow issues that surfaced in nucleus with filter menu buttons.
Before:
After:

ENG-144581 - Truncate buttons; Prevent table filter overflow

---

src/components/mx-table/mx-table.tsx

Using `max-content` sets the column widths to the unwrapped widths, which causes the grid to overflow the container width.

ENG-144581 - Set operations bar columns to auto so they wrap

---

src/components/mx-menu-item/mx-menu-item.tsx
src/components/mx-menu/mx-menu.tsx

- Added a watcher on `triggerEl` and `anchorEl` to ensure the menu trigger element gets the necessary ARIA attributes.
- Removed the redundant `tabindex` from menu items that are wrapped with a link.

Menu a11y changes

---

src/components/mx-confirm-input/mx-confirm-input.tsx
src/components/mx-date-picker/mx-date-picker.tsx
src/components/mx-dropdown-menu/mx-dropdown-menu.tsx
src/components/mx-input/mx-input.tsx
src/components/mx-select/mx-select.tsx
src/components/mx-time-picker/mx-time-picker.tsx

Keeping the `error` attribute for form components in sync with the prop ensures we can do things like `HTMLFormElement.querySelectorAll('[error]')` reliably.

ENG-144889 - Keep error attribute in sync with error property

---

src/components/mx-snackbar/mx-snackbar.tsx
src/tailwind/mx-snackbar/index.scss
src/tailwind/variables/index.scss
vuepress/components/snackbars.md

This updates the default text color of action buttons inside snackbars to use a new `--mds-text-snackbar-btn` variable.  The default value is a lighter blue that meets WCAG contrast requirements when used against the dark snackbar background, unlike the default color for text buttons.
I also added descriptions to the prop and event tables in the snackbar documentation.
Before:
After:

ENG-145350: Update snackbar button color, as well as documentation

---

src/components/mx-menu/mx-menu.tsx
vuepress/components/icons.md

A couple small fixes:
- The `role="menu"` attribute is now only added if a menu actually has child menu items.  This applies to autocomplete menus that can become empty when there are no matching items, for example.
- Fixed the auto-generated icon list on the Icon documentation page.  This broke when all the icon classes were scoped to the `.mds` container in a previous PR.

Fix icon list; Fix a11y issue with empty menus

---

vuepress/components/icons.md

This fixes the generated icon list (again).  The list worked fine when running `yarn dev`, but I'm really not sure how.  Neither [`StyleSheetList`](https://developer.mozilla.org/en-US/docs/Web/API/StyleSheetList) nor [`CCSRuleList`](https://developer.mozilla.org/en-US/docs/Web/API/CSSRuleList) support `forEach`, so they needed to be converted to arrays.
I also switched to using `CSSStyleSheet.cssRules` instead of `rules` because `rules` is deprecated apparently.
I built the docs and served them up locally to verify this fixes things.

Fix generated icon list

---

src/components/mx-icon-button/mx-icon-button.tsx
src/components/mx-icon-button/test/mx-icon-button.spec.tsx
vuepress/components/buttons.md

This updates `mx-icon-button` to have a `target` prop just like `mx-button` already has.
Once this change is in nucleus, the arrow button for a Quick Action will open the link in a new tab (matching the behavior of the text links).

Add `target` prop to icon buttons

---

src/components/mx-toggle-button-group/mx-toggle-button-group.tsx
vuepress/components/buttons.md
vuepress/components/inputs.md
vuepress/components/menus.md
vuepress/components/modals.md
vuepress/components/page-headers.md
vuepress/components/tables.md

- Fixed `mx-toggle-button-group` emitting `mxInput` even when a disabled toggle button is clicked.
- Removed all the `&bull;` bullets in the docs that were previously added when the tailwind reset was applied globally.

Fix disabled toggle button group still emitting `mxInput` events; Fix double bullets in docs

---

vuepress/.vuepress/styles/index.styl

This line was previously added when the tailwind preflight was scoped under `.mds`, but this was causing a weird double scrollbar issue on some pages, which in turn would sometimes cause the table row dragging to break.

Remove overflow rule that breaks layout

---

src/components/mx-table/mx-table.tsx

This adds better handling and warnings for these `mx-table` scenarios:
- **The `columns` prop is not provided for a custom templated table**: Instead of throwing an exception, the header row will now consist of only empty cells, and a warning will be shown in the console.
- **The `columns` prop does not have enough definitions for all the columns in the template**:  The extra columns will now have empty cells in the header row, and a different warning will be shown in the console.
- **Some (but not all) rows have more cells than are defined**:  An error will be shown in the console.

Add better handling for missing or invalid `columns` prop

---

src/components/mx-icon-button/mx-icon-button.tsx
src/tailwind/icons.scss
vuepress/components/buttons.md

An upward-pointing chevron icon button is needed for the notifications feature in nucleus.

Add `chevron-up` icon and `chevronUp` icon button

---

vuepress/components/modals.md

The fourth modal example was showing the code snippet for the fifth example.

Fix wrong snippet shown for modal example

---

src/components/mx-circular-progress/mx-circular-progress.tsx
src/components/mx-linear-progress/mx-linear-progress.tsx
vuepress/components/progress.md

This adds a `simulateProgressDuration` prop to the `mx-linear-progress` and `mx-circular-progress` components.
If given a duration of 500 milliseconds, for example, the component will artificially advance the progress 1% every 5ms, stopping at 99%.  The indicator will only show 100% once the `value` prop is set to `100`.
Addresses #204

Add `simulateProgressDuration` prop to progress indicators (#204)

---

package.json

This should hopefully address #206.  We needed to add `typesVersions` to the `package.json` to ensure there were typings for the `react` exports.

Fix React exports not working with typescript

---

src/components.d.ts
src/components/mc-button/mc-button.tsx
src/components/mc-checkbox/mc-checkbox.scss
src/components/mc-checkbox/mc-checkbox.tsx
src/components/mc-checkbox/test/mc-checkbox.spec.tsx
src/components/mc-radio/mc-radio.scss
src/components/mc-radio/mc-radio.tsx
src/components/mc-radio/test/mc-radio.spec.tsx
src/components/mc-range/mc-range.scss
src/components/mc-range/mc-range.tsx
src/components/mc-range/test/mc-range.spec.tsx
src/components/mc-toggle/mc-toggle.scss
src/components/mc-toggle/mc-toggle.tsx
src/components/mc-toggle/test/mc-toggle.spec.tsx
src/tailwind/styles.scss
src/tailwind/variables/index.scss
tailwind.config.js
vuepress/.vuepress/components/ComponentReadme.vue
vuepress/components/mc-checkbox/readme.md
vuepress/components/mc-radio/readme.md
vuepress/components/mc-range/readme.md
vuepress/components/mc-toggle/readme.md
vuepress/components/selection-controls.md
vuepress/css-documentation/typography.md

This adds the Mercury checkboxes, radio buttons, toggle switches, and range selectors for #215.
Per my comment in the typography PR, I've already run into a need for an arbitrary 14px font-size utility for the checkbox/radio/toggle labels, so I added a `.text-14` class to the tailwind config.  I also added a `.text-16` for the icons used in the `mc-button` component since `.text-subtitle` did not really feel appropriate even though it technically looked okay.  @iamjpg Let me know if you hate these `.text-16` and `.text-14` classes.  I'm hoping we won't need too many of these, and I think I like `.text-14` better than something like `.text-sm` since you can tell immediately what the pixel size is and it's similar to how we have `.h-14`, `.w-14`, etc.
I also updated the `ComponentReadme` …

Add Mercury selection controls

---

src/components/mc-icon-button/mc-icon-button.scss
src/components/mc-icon-button/mc-icon-button.tsx
src/components/mc-icon-button/test/mc-icon-button.spec.tsx
src/tailwind/icons.scss
src/tailwind/styles.scss
src/tailwind/variables/index.scss
vuepress/components/buttons.md
vuepress/components/mc-icon-button/readme.md

This adds the new `mc-icon-button` component.  The close button is needed to implement modals for #222.

Add Mercury icon buttons

---

src/components/mx-table/mx-table.tsx

This problem showed up in nucleus not long after I went on parental leave.
When you use the default slot of the `mx-table` component, it establishes a column count based on the number of `mx-table-cell` elements in the *first row*.  It uses this column count to create the CSS grid.
The problem would show up whenever you nested a row inside the *first row*, causing `rows[0].querySelectorAll('mx-table-cell')` to return both the top-level cells and the nested cells.
The fix is to simply change the selector to exclude cells that are inside nested rows.

OT-23 - Fix bad column count when first table row has nested rows

---

src/components/mx-table-row/mx-table-row.tsx

This addresses #227. Cypress mistakenly thinks some elements are not visible because we have combined `overflow: hidden` with `display: contents` on a parent element, which is admittedly unusual.

Do not combine `.overflow-hidden` with `.contents`

---

src/components/mx-table/mx-table.tsx

This is an additional fix for [OT-23](https://moxiworks.atlassian.net/browse/OT-23).  I previously changed the query for the first row's table cells to `mx-table-cell:not(mx-table-row mx-table-row mx-table-cell)` to avoid counting cells that are in a nested row.  However, this broke the counting of cells inside a subheader row, so this fixes that by adding a `:not([subheader])`.
This change should fix the admin Programs table in nucleus in the current `release-candidate` branch.

OT-23 - Fix column count when first row is subheader

---

src/utils/utils.ts

If a table is given a `null` cell value via the `rows` prop, the `isDateObject` helper blows up.  The `typeof val !== 'object'` check I already had wasn't enough since `typeof null` returns `'object'` (JavaScript, you so crazy).
The bad nucleus association data in QA has some null `boardname` values, which caused a table to not render at all.  I will also do another PR in nucleus to filter those null associations out.

OT-76 / OT-85 - Fix isDateObject exceptions when a table cell value is null/undefined

---

src/components/mx-table/mx-table.tsx

If a column has values that are a mix of numbers and strings like `30` and `'100'`, the table will effectively try to call `(30).localeCompare('100')`, which results in a `localeCompare is not a function` exception.
This PR prevents the exception by always converting values to strings once it is determined that they are not both numbers.  
For OT-94, I'm also [making a change to the affected table in nucleus](https://github.com/moxiworks/nucleus/pull/721) to use a custom `sortCompare`, which will avoid the exception AND sort the rows as expected.

OT-94 - Fix table sorting when a column has both string and number values

---

src/components/mx-tab/mx-tab.tsx

Something must have changed in Safari recently because the tabs went crazy.  In my testing, a `.min-w-full` class on the tab can be safely replaced with `.min-w-0` to address the issue.

Fix tab width on Safari

---

src/components/mx-menu/mx-menu.tsx

This adds `overflow: hidden` to the rounded menu element so that the inner scrollbar does not overflow, causing square corners on the right side of the menu.
https://moxiworks.atlassian.net/browse/OT-101

OT-101 - Fix scollbar square corners overflowing menu

---

src/components/mx-modal/mx-modal.tsx

Currently, if the `isOpen` prop is initially set to `true`, the modal will not open once the component loads.  This fixes that.

Allow modals to be initially open

---

packages/mds/src/components/mx-dropdown-menu/mx-dropdown-menu.tsx
packages/mds/src/components/mx-input/mx-input.tsx
packages/mds/src/components/mx-select/mx-select.tsx

Previously, the `mx-dropdown-menu`, `mx-select`, and `mx-input` components had a 1px border width when not focused and a 2px border width when focused (or when in an error state).
https://github.com/moxiworks/mds/pull/246 removed this change in border width, so the negative margins that were previously added to prevent layout shifts need to also be removed.

fix: remove negative margins on focused inputs

---

packages/mds/package.json
packages/mds/postcss.config.js
yarn.lock

Adds cssnano to help reduce css payload size, not only through better minification but also by unifying declarations and more - ref. https://cssnano.co/
Of particular interest here is the benefit when we're using @apply rules within scss files for tailwind classes, but note there's *many* optimisations: https://cssnano.co/docs/what-are-optimisations/
eg: if we have a class definition such as:
```
.leftIconWrapper {
@apply flex items-center h-full pl-16 space-x-16;
}
```
the current config would output multiple declarations of the same class like:
this would then become:
still not **_absolutely_** perfect - but much better

fix: Adds cssnano for better output and performance

---

packages/mds/src/components.d.ts
packages/mds/src/components/mx-block-input/mx-block-input.tsx
packages/mds/src/components/mx-block-input/test/mx-block-input.spec.tsx
packages/mds/src/components/mx-block-wrapper/mx-block-wrapper.tsx
packages/mds/src/components/mx-block-wrapper/test/mx-block-wrapper.spec.tsx
packages/mds/src/tailwind/mx-block-input/index.scss
packages/mds/src/tailwind/mx-block-wrapper/index.scss
packages/mds/src/tailwind/styles.css
packages/mds/vuepress/.vuepress/config.js
packages/mds/vuepress/components/block-inputs.md

Initial commit for block input component.
Currently this implements the Block Wrapper (a basic styled grid utility used to contain block input components) and the basic input (think: `<input>` replacement)
Will look at how we can re-use as much of the key pieces for other input types (selects, etc) and keep things dry but wanted to get some feedback on this one first.

feat: initial block input components

---

packages/mds-angular/package.json
packages/mds-angular/scripts/delete-output.sh

`ng`, the angular cli, builds a package.json into dist. I've chosen to ignore it and delete the file.
I did this incorrectly though as prepublish and prepack both run on publish. So by the time the 2nd ran, the file was deleted and it'd error.
So now the -f flag is used to ignore deleted files, and I removed the prepack cause it's not necessary

ENG-166245 - Fixed the prepublish script

---

packages/mds/src/tailwind/mx-button/index.scss

Just a small fix for the hover styling of `mx-button` when the `btn-type` is `contained` _and_ an `href` is provided (because `:enabled` doesn't work for `<a>`).

fix: contained link button hover styling
