moxiworks/mds

src/tailwind/mx-button/index.scss, src/tailwind/mx-checkbox/index.scss, src/tailwind/mx-input/index.scss, src/tailwind/mx-radio/index.scss, src/tailwind/mx-switch/index.scss, src/tailwind/mx-tab/index.scss, src/tailwind/mx-toggle-button/index.scss, src/tailwind/variables/index.scss, tailwind.config.js, vuepress/components/buttons.md, vuepress/components/inputs.md, vuepress/components/selection-controls.md, vuepress/components/tabs.md, vuepress/css-documentation/colors.md, vuepress/css-documentation/sizing/height.md, vuepress/css-documentation/sizing/width.md, vuepress/examples/flex.md, vuepress/examples/grid.md
We'll need to continue to work on this and work out all the branding, etc., but I figured I'd go ahead and PR what I have so I can continue building on this pattern for the components I haven't finished.
- Created variables for all colors used by components, so they can be overwritten / rebranded as needed in the future.  The values of the variables are all just raw hex/rgba for now; we can always change this later.
- Added the full variable list to the Colors page of the docs.
- Added variables to component pages in the docs using regions within the variable list.
- Tweaked the configuration and naming of the existing primary/secondary/gray colors.
=> ENG-132178 - Move component colors to CSS variables

src/components/mx-button/mx-button.tsx, src/components/mx-button/test/mx-button.spec.tsx, src/components/mx-icon-button/mx-icon-button.tsx, src/components/mx-icon-button/test/mx-icon-button.spec.tsx
=> Add formaction prop to buttons and icon buttons

src/components/mx-radio/mx-radio.tsx, src/components/mx-radio/test/mx-radio.spec.tsx, src/components/mx-switch/mx-switch.tsx, src/components/mx-switch/test/mx-switch.spec.tsx, src/tailwind/mx-radio/index.scss, src/tailwind/mx-switch/index.scss, src/tailwind/variables/index.scss, vuepress/components/selection-controls.md
=> ENG-141470 - Add disabled prop to mx-switch and mx-radio

src/components/mx-chip-group/mx-chip-group.tsx, src/components/mx-chip/mx-chip.tsx, src/components/mx-date-picker/mx-date-picker.tsx, src/components/mx-dialog/mx-dialog.tsx, src/components/mx-dialog/test/mx-dialog.spec.tsx, src/components/mx-menu-item/mx-menu-item.tsx, src/components/mx-menu-item/test/mx-menu-item.spec.tsx, src/components/mx-modal/mx-modal.tsx, src/components/mx-modal/test/mx-modal.spec.tsx, src/components/mx-tab-content/mx-tab-content.tsx, src/components/mx-table-cell/mx-table-cell.tsx, src/components/mx-table-row/mx-table-row.tsx, src/components/mx-table/mx-table.tsx, src/components/mx-time-picker/mx-time-picker.tsx, src/components/mx-toggle-button-group/mx-toggle-button-group.tsx, src/components/mx-toggle-button/mx-toggle-button.tsx
This PR addresses most of the issues that [axe](https://www.deque.com/axe/devtools/) was able to detect.
Still to come in future PRs:
- Rename `aria-label` _prop_ so the host element doesn't effectively have an `aria-label` _attribute_.
- Fix nested focusable elements in `mx-chip`.
- Make examples use best practices even if it clutters up the sample code a bit.
=> ENG-141588 - Address minor accessibility issues

src/components/mx-table/mx-table.tsx, src/tailwind/mx-table/index.scss, vuepress/components/tables.md
This is needed for the products admin list in nucleus.
=> ENG-141902 - Add footer slot to table

src/components/mx-icon-button/mx-icon-button.tsx, src/tailwind/mx-icon-button/index.scss
This fixes issues with the icon button having the wrong color.
=> Fix icon button color

src/components/mx-button/test/mx-button.spec.tsx, src/tailwind/styles.css, src/utils/utils.ts
My fix in https://github.com/moxiworks/mds/pull/123 wasn't quite right.  I've updated a unit test for this to be sure that I've really got it this time.  I'm also updating our Google Fonts Open Sans URL to include regular italics, so our italic text looks more like the designs and not so ugly.
=> ENG-141900 - Hyphenated data attribute fix

src/utils/utils.ts
This is yet another fix related to the data attribute propagation.
=> ENG-141900 - Remove propagated data attrib from host element

src/components/mx-time-picker/mx-time-picker.tsx, src/components/mx-time-picker/test/mx-time-picker.spec.tsx
This fixes ugly, but valid, time input values.
=> ENG-142051 - Normalize time picker value

src/components/mx-date-picker/mx-date-picker.tsx, src/components/mx-date-picker/test/mx-date-picker.spec.tsx, vuepress/components/pickers.md
=> ENG-142501 - Add min/max/allowFuture/allowPast props

src/components/mx-banner/mx-banner.tsx
Hopefully this does the trick for good.
=> Add min-w-0 class to fix overflow ellipsis

src/components.d.ts, src/components/mx-dropdown-menu/mx-dropdown-menu.tsx, src/components/mx-dropdown-menu/test/mx-dropdown-menu.spec.tsx, src/tailwind/mx-dropdown-menu/index.scss
It's been a while since I've written code in here so be gentle :) If you wanna scrap it for a better implementation tomorrow I'm 100% cool with that.
=> Mx-Dropdown Error Property

vuepress/components/pickers.md
Satisfies https://github.com/moxiworks/mds/issues/185
=> Example of Populating Pickers with Current Date/Time as a Default

vuepress/.vuepress/config.js, vuepress/.vuepress/styles/index.styl, vuepress/.vuepress/styles/palette.styl, vuepress/getting-started.md, vuepress/index.md
- Updated the landing page to include a few quick links for each section
- Updated the vuepress styling to match the design system (primary color and font family)
- Added a GitHub link to the nav
- Small changes to the Getting Started page
=> Update landing page and vuepress styles

.gitignore, build-all.sh, package.json, react/package.json, react/tsconfig.json, stencil.config.ts, vuepress/getting-started.md
Hopefully this all works once it is built in the real world. 🤞
=> Export react wrapper components 🎉

.gitignore, package.json, react/package.json, readme.md, stencil.config.ts
Adding hydration support for users of frameworks like NextJS in the case they want to write their own custom SSR Hydration logic.
Also fixed a bunch of TS errors in the build by updating libraries inside of the react folder.
=> Adding Hydration Support + Typescript Error Fixes

package.json, react/package.json, readme.md, stencil.config.ts
Essentially cherry picking the hydration and TS updates from the main branch PR earlier this week.
=> Adding hydration and typescript fixes to the MDS Redesign branch.

.yarnrc.yml, packages/mds/package.json, packages/mds/vuepress/getting-started-cdn-example.html
=> ENG-165636 - Setup npm release and bumped version

packages/mds/src/tailwind/styles.css, packages/mds/vuepress/.vuepress/styles/index.styl
Replaces Open Sans with Roboto throughout and updates _some_ of the font weights in the docs
=> fix: Update font to Roboto

.buildkite/pipeline.yml, .yarnrc.yml, README.md, lerna.json, package.json, yarn.lock
This commit adds publish. I expect this to fail in all honesty but that's okay, I'll use the error messages to fix in a later release
=> ENG-166243 - Added auto publish 

.buildkite/pipeline.yml, package.json, packages/mds/.stylelintrc, packages/mds/package.json, packages/mds/src/tailwind/base.scss, packages/mds/src/tailwind/mx-banner/index.scss, packages/mds/src/tailwind/mx-checkbox/index.scss, packages/mds/src/tailwind/mx-chip/index.scss, packages/mds/src/tailwind/mx-date-picker/index.scss, packages/mds/src/tailwind/mx-menu-item/index.scss, packages/mds/src/tailwind/mx-pagination/index.scss, packages/mds/src/tailwind/mx-radio/index.scss, packages/mds/src/tailwind/mx-search/index.scss, packages/mds/src/tailwind/mx-switch/index.scss, packages/mds/src/tailwind/mx-table/index.scss, packages/mds/src/tailwind/mx-time-picker/index.scss, yarn.lock
Adds stylelint with some basic rules (and exclusions)
Fixes existing stylelint errors
=> UX-226 add stylelint

packages/mds/src/components.d.ts, packages/mds/src/components/mx-checkbox/mx-checkbox.tsx, packages/mds/src/components/mx-radio/mx-radio.tsx, packages/mds/src/tailwind/mx-checkbox/index.scss, packages/mds/src/tailwind/mx-radio/index.scss
Adds checkbox and radio input interactions
=> UX-218 Update checkbox and radio styling

packages/mds/src/components/mx-table/mx-table.tsx, packages/mds/src/tailwind/mx-checkbox/index.scss, packages/mds/src/tailwind/mx-icon-button/index.scss, packages/mds/src/tailwind/mx-input/index.scss, packages/mds/src/tailwind/mx-menu-item/index.scss, packages/mds/src/tailwind/mx-switch/index.scss, packages/mds/src/tailwind/mx-table/index.scss
Adds border to tables and updates table headers styling (typography and icon for sorting)
=> UX-230 data tables styling

packages/mds/src/components/mx-button/mx-button.tsx, packages/mds/src/components/mx-button/test/mx-button.spec.tsx, packages/mds/src/components/mx-dialog/mx-dialog.tsx, packages/mds/src/components/mx-modal/mx-modal.tsx, packages/mds/src/components/mx-page-header/mx-page-header.tsx, packages/mds/src/tailwind/mx-button/index.scss, packages/mds/vuepress/components/dialogs.md
Update dialog and modal styling
=> UX-219 update dialog and modal styling

packages/mds/src/components.d.ts, packages/mds/src/components/mx-switch/mx-switch.tsx, packages/mds/src/tailwind/mx-switch/index.scss, packages/mds/src/tailwind/variables/index.scss
Updates styling of toggles (switches) to Mercury look:
=> UX-221 update toggle styling

packages/mds/src/tailwind/mx-checkbox/index.scss, packages/mds/src/tailwind/mx-radio/index.scss, packages/mds/src/tailwind/variables/index.scss
Reintroduces focus state to new styling of checkboxes and radio inputs
=> UX-229 focus states

packages/mds/vuepress/.vuepress/config.js
=> chore: fix? favicon with path

packages/mds/src/tailwind/mx-banner/index.scss, packages/mds/src/tailwind/mx-snackbar/index.scss
Fixes the color of text buttons in banners and snackbars
=> fix: corrects text button colors

.npmrc, .npmrc.docker, ops/ci/Dockerfile, packages/mds/README.md
Struggling with the npmrc, I believe it needs to be in `root`. 
Needed to change the README to force a release
=> ENG-166245 - Force a publish with updated npmrc

packages/mds-angular/package.json
We need the correct package.json inputs
=> ENG-166245 - Updated the angular package

packages/mds/stencil.config.ts
Enabled the import injection flag that allows bundlers to lazy load conditionally when hot reload is on
=> ENG-166411 - Enabled import injection

packages/mds-angular/package.json, packages/mds-react/package.json
Followed the docs and ran tests to make sure the exports are correct.
It's hard to test the angular as it's exported but pretty certain I've got it
=> ENG-166245 - Updated the Angular and React exports
